name: Simon and Faye Lee Foundation
favicon: null
layout_spectrum: 0.9370914287865162
typography_spectrum: 0.7523708508815616
title: Simon and Faye Lee Foundation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.06075415946543217
  lightness: 0.7196495600510389
  saturation: 0.5710032172501087
  rhythmicContrast: 0.2892312118783593
purpose: []
